language: cpp
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest
before_install:
- sudo add-apt-repository -y ppa:dns/gnu
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qqy automake gcc libcppunit-dev valgrind
before_script:
- CXXFLAGS='-O3' ./bootstrap
