language: cpp
compiler:
- gcc
- clang
env:
  global:
    secure: JkEkyj21IHXBNLlhB1+XtBbkefEAmJuyMs8UDrUtQz4cV/Y9hiDLfI/c9bOZ72jT+dYbTDQM4cwrTXBZxGcKHYI7PrW+PHNHBZAZm0GKgBvQz7pzQXtqympSznsWUh0NkpDicRFI9fmpfSoEPn2SOCZ9EaV0h9DT+WDCnA08oYk=
script: CXXFLAGS='-O3' ./bootstrap && make travis-test
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-all-dev libcppunit-dev
after_success:
- git config --global user.email "${GH_EMAIL}"
- git config --global user.name "${GH_NAME}"
- cd scrm; 
  git remote rm origin;
  git remote add origin "https://${GH_TOKEN}@github.com/paulstaab/scrm"
- cd scrm; .travis/deploy.sh
