language: cpp
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- make doxygen-run
- ./tests/test_binaries.sh
- make algorithmtest
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcppunit-dev valgrind
before_script:
- CXXFLAGS='-O3' ./bootstrap
