language: cpp
env:
  global:
    secure: GvgROh8aSriDE1lTsoy1t193dzyFOdPtRFXwXb6+tx1yJijc37dnU9B5rpimH3mtoc0iTpVXrkD1Y+6aqIvN/CRLGWEYmLLwCLXScmQjTPBXWC1htGWlCKvibPdXi0A0qHWMGuXlYgvf2/bcWJidvx06KF/8lSKic+f+LN9X0Uo=
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest
before_install:
- sudo add-apt-repository -y ppa:dns/gnu
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qqy automake g++-4.8 libcppunit-dev valgrind
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
- g++ --version
before_script:
- CXXFLAGS='-O3' ./bootstrap
after_success:
- .travis/deploy.sh
