language: cpp
compiler:
- gcc
- clang
env:
  global:
    secure: JkEkyj21IHXBNLlhB1+XtBbkefEAmJuyMs8UDrUtQz4cV/Y9hiDLfI/c9bOZ72jT+dYbTDQM4cwrTXBZxGcKHYI7PrW+PHNHBZAZm0GKgBvQz7pzQXtqympSznsWUh0NkpDicRFI9fmpfSoEPn2SOCZ9EaV0h9DT+WDCnA08oYk=
script: 
- make scrm scrm_dbg
#- make unittests
#- make algorithmtests
#- ./tests/test_binaries.sh
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-all-dev libcppunit-dev
before_script:
- CXXFLAGS='-O3' ./bootstrap
after_success:
- ./.travis/deploy.sh
