language: cpp
compiler:
    - gcc
    - clang
# Change this to your needs
script: ./bootstrap && make check
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-all-dev doxygen libcppunit-dev 
