language: cpp
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest
before_install:
- sudo add-apt-repository -y ppa:dns/gnu
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qqy automake gcc-4.8 libcppunit-dev valgrind
- export CXX='g++-4.8'
before_script:
- CXXFLAGS='-O3' ./bootstrap
