language: cpp
compiler:
    - gcc
    - clang
# Change this to your needs
script: CXXFLAGS='-O3' ./bootstrap && make travis-test 
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-all-dev libcppunit-dev
